3.6.1

In [3]:
import numpy as np

# Bài 3.6
# 1. Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full((3, 3), True)
print("arr:\n", arr)

arr:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


3.6.2

In [4]:
# 2. Cho arr_ID = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ
# arr_ID, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.
arr_ID = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_ID.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("arr_2D sau khi đổi cột:\n", arr_2D)

arr_2D sau khi đổi cột:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


3.6.3

In [5]:
# 3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("arr_2D sau khi đổi dòng:\n", arr_2D)

arr_2D sau khi đổi dòng:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


3.6.4

In [6]:
# 4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.
arr_2D = np.flip(arr_2D, axis=0)
print("arr_2D sau khi đảo ngược dòng:\n", arr_2D)

arr_2D sau khi đảo ngược dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]


3.6.5

In [7]:
# 5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.
arr_2D = np.flip(arr_2D, axis=1)
print("arr_2D sau khi đảo ngược cột:\n", arr_2D)

arr_2D sau khi đảo ngược cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]


3.6.6

In [8]:
# 6. Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]),
# Kiểm tra trong array có giá trị rỗng không?
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
if np.isnan(arr_2D_null).any():
    print("Có giá trị NaN trong arr_2D_null")

Có giá trị NaN trong arr_2D_null


3.6.7

In [2]:
# 7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.
arr_2D_null = np.nan_to_num(arr_2D_null)
print("arr_2D_null sau khi thay thế NaN:\n", arr_2D_null)

arr_2D_null sau khi thay thế NaN:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
